# Generated by Django 4.2.14 on 2024-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('aa_contacts', '0003_corporationcontact_is_watched_corporationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpStandingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('standing', models.FloatField()),
                ('comparison', models.CharField(choices=[('>', 'Greater Than'), ('>=', 'Greater Or Equal'), ('<', 'Less Than'), ('<=', 'Less Or Equal'), ('=', 'Equal')], max_length=2)),
                ('corporations', models.ManyToManyField(help_text='The corporations that have set the standings', related_name='corp_standing_filters', to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Corp Standings',
                'verbose_name_plural': 'Smart Filter: Corp Standings',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AllianceStandingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('standing', models.FloatField()),
                ('comparison', models.CharField(choices=[('>', 'Greater Than'), ('>=', 'Greater Or Equal'), ('<', 'Less Than'), ('<=', 'Less Or Equal'), ('=', 'Equal')], max_length=2)),
                ('alliances', models.ManyToManyField(help_text='The alliances that have set the standings', related_name='alliance_standing_filters', to='eveonline.eveallianceinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Alliance Standings',
                'verbose_name_plural': 'Smart Filter: Alliance Standings',
                'default_permissions': (),
            },
        ),
    ]
