# Generated by Django 5.2.14 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_contacts', '0005_standingfilter_check_type_standingfilter_only_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancetoken',
            name='last_modified_contacts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoken',
            name='last_modified_labels',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporationtoken',
            name='last_modified_contacts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporationtoken',
            name='last_modified_labels',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
