# Generated by Django 5.2.14 on 2026-06-13 10:05

import aa_contacts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_contacts', '0006_alliancetoken_last_modified_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('manage_alliance_contacts', 'Can manage alliance contacts'), ('manage_corporation_contacts', 'Can manage corporation contacts'), ('view_alliance_notes', 'Can view notes on alliance contacts'), ('view_corporation_notes', 'Can view notes on corporation contacts'), ('view_alliance_server_links', 'Can view server links on alliance contacts'), ('view_corporation_server_links', 'Can view server links on corporation contacts'))},
        ),
        migrations.CreateModel(
            name='AllianceContactServerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', aa_contacts.models.AnySchemeURLField(max_length=500)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_links', to='aa_contacts.alliancecontact')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CorporationContactServerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', aa_contacts.models.AnySchemeURLField(max_length=500)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_links', to='aa_contacts.corporationcontact')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
