/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contacts/api/alliances/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_alliance_tokens_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/tokens/{alliance_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single */
        get: operations["aa_contacts_api_alliance_tokens_get_single"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["aa_contacts_api_alliance_contacts_list_contacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Contacts */
        post: operations["aa_contacts_api_alliance_contacts_update_contacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/{contact_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Contact */
        patch: operations["aa_contacts_api_alliance_contacts_edit_contact"];
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/{contact_pk}/server-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Server Link */
        post: operations["aa_contacts_api_alliance_contacts_create_server_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/{contact_pk}/server-links/{link_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Server Link */
        put: operations["aa_contacts_api_alliance_contacts_update_server_link"];
        post?: never;
        /** Delete Server Link */
        delete: operations["aa_contacts_api_alliance_contacts_delete_server_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_corporation_tokens_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/tokens/{corporation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single */
        get: operations["aa_contacts_api_corporation_tokens_get_single"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["aa_contacts_api_corporation_contacts_list_contacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Contacts */
        post: operations["aa_contacts_api_corporation_contacts_update_contacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/{contact_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Contact */
        patch: operations["aa_contacts_api_corporation_contacts_edit_contact"];
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/{contact_pk}/server-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Server Link */
        post: operations["aa_contacts_api_corporation_contacts_create_server_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/{contact_pk}/server-links/{link_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Server Link */
        put: operations["aa_contacts_api_corporation_contacts_update_server_link"];
        post?: never;
        /** Delete Server Link */
        delete: operations["aa_contacts_api_corporation_contacts_delete_server_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/permissions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["aa_contacts_api_permissions_get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllianceTokenSchema */
        AllianceTokenSchema: {
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            alliance: components["schemas"]["EveAllianceSchema"];
        };
        /** EveAllianceSchema */
        EveAllianceSchema: {
            /** Logo Url */
            logo_url: string;
            /** Alliance Id */
            alliance_id: number;
            /**
             * Alliance Name
             * @description Alliance's name
             */
            alliance_name: string;
        };
        /**
         * Color
         * @enum {string}
         */
        Color: "primary" | "secondary" | "success" | "danger" | "warning" | "info" | "light" | "dark";
        /** ContactLabelSchema */
        ContactLabelSchema: {
            /** Label Name */
            label_name: string;
        };
        /** ContactSchema */
        ContactSchema: {
            /** Id */
            id: number;
            /** Contact Id */
            contact_id: number;
            contact_type: components["schemas"]["ContactTypeOptions"];
            /** Contact Logo Url */
            contact_logo_url: string;
            /** Contact Name */
            contact_name: string;
            /** Standing */
            standing: number;
            /** Notes */
            notes?: string | null;
            /** Can Edit Notes */
            can_edit_notes: boolean;
            /**
             * Labels
             * @default []
             */
            labels: components["schemas"]["ContactLabelSchema"][];
            /** Can View Server Links */
            can_view_server_links: boolean;
            /** Can Manage Server Links */
            can_manage_server_links: boolean;
            /**
             * Server Links
             * @default []
             */
            server_links: components["schemas"]["ServerLinkSchema"][];
        };
        /**
         * ContactTypeOptions
         * @enum {string}
         */
        ContactTypeOptions: "character" | "corporation" | "alliance" | "faction";
        /** ServerLinkSchema */
        ServerLinkSchema: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Password */
            password: string;
            color: components["schemas"]["Color"];
            /** Id */
            id: number;
        };
        /** UpdateContactSchema */
        UpdateContactSchema: {
            /** Notes */
            notes: string;
        };
        /** ServerLinkInputSchema */
        ServerLinkInputSchema: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Password
             * @default
             */
            password: string;
            /** @default secondary */
            color: components["schemas"]["Color"];
        };
        /** CorporationTokenSchema */
        CorporationTokenSchema: {
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            corporation: components["schemas"]["EveCorporationSchema"];
        };
        /** EveCorporationSchema */
        EveCorporationSchema: {
            alliance?: components["schemas"]["EveAllianceSchema"] | null;
            /** Logo Url */
            logo_url: string;
            /** Corporation Id */
            corporation_id: number;
            /**
             * Corporation Name
             * @description Corporation's name
             */
            corporation_name: string;
        };
        /** UserPermissionsSchema */
        UserPermissionsSchema: {
            /** Can Manage Alliance Contacts */
            can_manage_alliance_contacts: boolean;
            /** Can Manage Corporation Contacts */
            can_manage_corporation_contacts: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aa_contacts_api_alliance_tokens_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceTokenSchema"][];
                };
            };
        };
    };
    aa_contacts_api_alliance_tokens_get_single: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceTokenSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_list_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_update_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_edit_contact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_create_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerLinkInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLinkSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_update_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                link_pk: number;
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerLinkInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLinkSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_delete_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                link_pk: number;
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_tokens_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationTokenSchema"][];
                };
            };
        };
    };
    aa_contacts_api_corporation_tokens_get_single: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationTokenSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_list_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_update_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_edit_contact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_create_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerLinkInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLinkSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_update_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                link_pk: number;
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerLinkInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLinkSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_delete_server_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_pk: number;
                link_pk: number;
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_permissions_get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPermissionsSchema"];
                };
            };
        };
    };
}
