/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contacts/api/alliance/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_alliance_token_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporation/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_corporation_token_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllianceTokenSchema */
        AllianceTokenSchema: {
            /** Id */
            id: number;
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            alliance: components["schemas"]["EveAllianceSchema"];
        };
        /** EveAllianceSchema */
        EveAllianceSchema: {
            /** Logo Url */
            logo_url: string;
            /** Alliance Id */
            alliance_id: number;
            /** Alliance Name */
            alliance_name: string;
        };
        /** CorporationTokenSchema */
        CorporationTokenSchema: {
            /** Id */
            id: number;
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            corporation: components["schemas"]["EveCorporationSchema"];
        };
        /** EveCorporationSchema */
        EveCorporationSchema: {
            alliance?: components["schemas"]["EveAllianceSchema"] | null;
            /** Logo Url */
            logo_url: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aa_contacts_api_alliance_token_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceTokenSchema"][];
                };
            };
        };
    };
    aa_contacts_api_corporation_token_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationTokenSchema"][];
                };
            };
        };
    };
}
