/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contacts/api/alliances/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_alliance_tokens_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/tokens/{alliance_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single */
        get: operations["aa_contacts_api_alliance_tokens_get_single"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/alliances/{alliance_id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["aa_contacts_api_alliance_contacts_list_contacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get List */
        get: operations["aa_contacts_api_corporation_tokens_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/tokens/{corporation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single */
        get: operations["aa_contacts_api_corporation_tokens_get_single"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/api/corporations/{corporation_id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["aa_contacts_api_corporation_contacts_list_contacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllianceTokenSchema */
        AllianceTokenSchema: {
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            alliance: components["schemas"]["EveAllianceSchema"];
        };
        /** EveAllianceSchema */
        EveAllianceSchema: {
            /** Logo Url */
            logo_url: string;
            /** Alliance Id */
            alliance_id: number;
            /** Alliance Name */
            alliance_name: string;
        };
        /** ContactLabelSchema */
        ContactLabelSchema: {
            /** Label Name */
            label_name: string;
        };
        /** ContactSchema */
        ContactSchema: {
            /** Contact Id */
            contact_id: number;
            contact_type: components["schemas"]["ContactTypeOptions"];
            /** Contact Logo Url */
            contact_logo_url: string;
            /** Contact Name */
            contact_name: string;
            /** Standing */
            standing: number;
            /** Notes */
            notes?: string | null;
            /**
             * Labels
             * @default []
             */
            labels: components["schemas"]["ContactLabelSchema"][];
        };
        /**
         * ContactTypeOptions
         * @enum {string}
         */
        ContactTypeOptions: "character" | "corporation" | "alliance" | "faction";
        /** CorporationTokenSchema */
        CorporationTokenSchema: {
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            corporation: components["schemas"]["EveCorporationSchema"];
        };
        /** EveCorporationSchema */
        EveCorporationSchema: {
            alliance?: components["schemas"]["EveAllianceSchema"] | null;
            /** Logo Url */
            logo_url: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aa_contacts_api_alliance_tokens_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceTokenSchema"][];
                };
            };
        };
    };
    aa_contacts_api_alliance_tokens_get_single: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceTokenSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_alliance_contacts_list_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_tokens_get_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationTokenSchema"][];
                };
            };
        };
    };
    aa_contacts_api_corporation_tokens_get_single: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationTokenSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aa_contacts_api_corporation_contacts_list_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
